### ISSUE TITLE
Unexpected response from Steam

### ISSUE THREAD

**Issue by ivandrago228** [waylaidwanderer/PHP-SteamCommunity#33]
Have a problem after tuesday maintenance. Could you fix it?

```
Uncaught exception 'waylaidwanderer\SteamCommunity\SteamException' with message 'Unexpected response from Steam.' in /vendor/waylaidwanderer/php-steamcommunity/SteamCommunity.php:279
Stack trace:
#0 /vendor/waylaidwanderer/php-steamcommunity/SteamCommunity.php(74): waylaidwanderer\SteamCommunity\SteamCommunity->_setSession()
#1 /vendor/waylaidwanderer/php-steamcommunity/SteamCommunity.php(69): waylaidwanderer\SteamCommunity\SteamCommunity->__construct(Array, '/vendor/...', true)
#2 /vendor/waylaidwanderer/php-steamcommunity/Examples/ExampleBot.php(19): waylaidwanderer\SteamCommunity\SteamCommunity->__construct(Array, '/vendor/...')
#3 {main}
  thrown in /vendor/waylaidwanderer/php-steamcommunity/SteamCommunity.php on line 279
```

**Comment by CyanoFresh** [comment]
maybe related to #24 . Try debug steam response

**Comment by ivandrago228** [comment]
Fixed, thank you :)
